name: Build LaTeX PDFs

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Detect changed top-level directories
        id: changed_dirs
        shell: bash
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            # For tag pushes, rebuild all directories
            CHANGED_DIRS=$(find . -mindepth 1 -maxdepth 1 -type d -not -path '*/\.*' | sed 's|^\./||')
          else
            # For main branch commits, only rebuild changed directories
            CHANGED_DIRS=$(git diff --name-only HEAD~1 HEAD | cut -d/ -f1 | sort -u)
          fi

          echo "Changed directories:"
          echo "$CHANGED_DIRS"
          echo "dirs<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_DIRS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Find standalone .tex files (those with \\documentclass)
        id: find_tex
        shell: bash
        run: |
          TEX_FILES=""
          for d in ${{ steps.changed_dirs.outputs.dirs }}; do
            if [ -d "$d" ]; then
              for f in $(find "$d" -maxdepth 1 -type f -name "*.tex"); do
                if grep -q '\\documentclass' "$f"; then
                  TEX_FILES+="$f"$'\n'
                fi
              done
            fi
          done

          if [ -z "$TEX_FILES" ]; then
            echo "No standalone TeX files found."
            exit 0
          fi

          echo "Standalone TeX files to compile:"
          echo "$TEX_FILES"
          echo "tex_files<<EOF" >> $GITHUB_OUTPUT
          echo "$TEX_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Compile LaTeX files
        if: steps.find_tex.outputs.tex_files != ''
        uses: xu-cheng/latex-action@v4
        with:
          root_file: ${{ steps.find_tex.outputs.tex_files }}
          work_in_root_file_dir: true
          extra_system_packages: "inkscape ghostscript"

      - name: List generated PDFs
        run: find . -type f -name "*.pdf"

      - name: Upload PDFs as workflow artifacts
        uses: actions/upload-artifact@v4
        if: steps.find_tex.outputs.tex_files != ''
        with:
          name: Compiled-PDFs
          path: "**/*.pdf"

      - name: Create GitHub Release (tag builds only)
        uses: softprops/action-gh-release@v2.4.1
        if: github.ref_type == 'tag' && steps.find_tex.outputs.tex_files != ''
        with:
          files: "**/*.pdf"
          body_path: CHANGELOG.txt
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
