name: LaTeX Workflow

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Detect changed top-level directories
        id: changed_dirs
        shell: bash
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            # For tag pushes, rebuild all directories
            CHANGED_DIRS=$(find . -mindepth 1 -maxdepth 1 -type d -not -path '*/\.*' | sed 's|^\./||')
          else
            # For main branch commits, only rebuild changed directories
            CHANGED_DIRS=$(git diff --name-only HEAD~1 HEAD | cut -d/ -f1 | sort -u)
          fi

          echo "Changed directories:"
          echo "$CHANGED_DIRS"

          # Use the GITHUB_OUTPUT file to set a multi-line output safely
          if [ -n "${GITHUB_OUTPUT:-}" ]; then
            echo "dirs<<EOF" >> "$GITHUB_OUTPUT"
            printf '%s\n' "$CHANGED_DIRS" >> "$GITHUB_OUTPUT"
            echo "EOF" >> "$GITHUB_OUTPUT"
          else
            # Fallback for very old runners (deprecated)
            echo "::set-output name=dirs::$CHANGED_DIRS"
          fi

      - name: Find standalone .tex files (those with \\documentclass)
        id: find_tex
        shell: bash
        run: |
          TEX_FILES=""
          for d in ${{ steps.changed_dirs.outputs.dirs }}; do
            if [ -d "$d" ]; then
              # find each .tex in the top of the directory
              while IFS= read -r f; do
                if grep -q '\\documentclass' "$f"; then
                  TEX_FILES+="$f"$'\n'
                fi
              done < <(find "$d" -maxdepth 1 -type f -name "*.tex")
            fi
          done

          if [ -z "$TEX_FILES" ]; then
            echo "No standalone TeX files found."
            # Exit successfully so the workflow doesn't fail
            exit 0
          fi

          echo "Standalone TeX files to compile:"
          printf '%s\n' "$TEX_FILES"

          if [ -n "${GITHUB_OUTPUT:-}" ]; then
            echo "tex_files<<EOF" >> "$GITHUB_OUTPUT"
            printf '%s\n' "$TEX_FILES" >> "$GITHUB_OUTPUT"
            echo "EOF" >> "$GITHUB_OUTPUT"
          else
            echo "::set-output name=tex_files::$TEX_FILES"
          fi

      - name: Compile LaTeX files
        if: steps.find_tex.outputs.tex_files != ''
        uses: xu-cheng/latex-action@v4
        with:
          root_file: ${{ steps.find_tex.outputs.tex_files }}
          work_in_root_file_dir: true
          extra_system_packages: "inkscape ghostscript"

      - name: List generated PDFs
        run: find . -type f -name "*.pdf"

      - name: Upload PDFs as workflow artifacts
        uses: actions/upload-artifact@v4
        if: steps.find_tex.outputs.tex_files != ''
        with:
          name: Compiled-PDFs
          path: "**/*.pdf"

      - name: Create GitHub Release (tag builds only)
        uses: softprops/action-gh-release@v2.4.1
        if: github.ref_type == 'tag' && steps.find_tex.outputs.tex_files != ''
        with:
          files: "**/*.pdf"
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
